### ISSUE TITLE
Overwrite previous benchmarks?

### ISSUE THREAD

**Issue by henry2004y** [henry2004y/TestParticle.jl#115]
https://github.com/henry2004y/TestParticle.jl/blob/6236aa752a73092366aaf69e98d2651cd1fd62ea/.github/workflows/benchmark.yml#L27-L32

The current benchmark bot writes a new report for every new push. Can we do something similar to the codecov bot which overwrite the previous report @TCLiuu?

**Comment by TCLiuu** [comment]
Okay, I will try to resolve this issue when I have free time. 

Say something off-topic, due to limitations in energy and some trivial matters in life, I haven't been able to contribute further improvements to this project in the past year. This is very regrettable because I am very interested in what this project aims to achieve. I will take responsibility for the parts that I have completed, so please feel free to contact me if there are any issues. I will find time to resolve them. The issues and features that I have proposed, hopefully one day I will be able to solve or achieve them.

**Comment by henry2004y** [comment]
Closed via #206
