### ISSUE TITLE
Relativistic equation

### ISSUE THREAD

**Issue by Beforerr** [henry2004y/TestParticle.jl#198]
The equation $\frac{\mathrm{d}v^i}{\mathrm{d}t} = \frac{q}{m \gamma^3}(E^i+\epsilon^{ijk}v_j B_k)$ does not feel right. For the case of zero-electric field, the γ is constant, and the equation $\frac{\mathrm{d}(\gamma v^i)}{\mathrm{d}t} = \frac{q}{m}(\epsilon^{ijk}v_j B_k)$ reduces to $\frac{\mathrm{d}v^i}{\mathrm{d}t} = \frac{q}{m \gamma}(\epsilon^{ijk}v_j B_k)$.

**Comment by henry2004y** [comment]
This is related to https://github.com/henry2004y/TestParticle.jl/issues/34. I attached the discussion we had for your reference.
[讨论记录 - 相对论粒子.pdf](https://github.com/user-attachments/files/17481853/-.pdf)

**Comment by Beforerr** [comment]
![image](https://github.com/user-attachments/assets/c5e35308-7042-4d70-ae83-b33fd58f4373)
The three steps are not right. First it should be $\gamma^3$ in the second line, and also $\vec{v} \vec{v} \neq  v^2$

**Comment by henry2004y** [comment]
$$
\begin{aligned}
\frac{\mathrm{d}\gamma}{\mathrm{d}t} &= -\frac{1}{2}\left( 1-\frac{v^2}{c^2} \right)^{-3/2}\frac{\mathrm{d}}{\mathrm{d}t}\left( 1-\frac{v^2}{c^2} \right) \\
&= -\frac{1}{2}\left( 1-\frac{v^2}{c^2} \right)^{-3/2} \left( -\frac{1}{c^2} \right) 2\vec{v}\cdot\frac{\mathrm{d}\vec{v}}{\mathrm{d}t} \\
&= \frac{\gamma^3 \vec{v}}{c^2}\cdot\frac{\mathrm{d}\vec{v}}{\mathrm{d}t}
\end{aligned}
$$
so
$$
\begin{aligned}
\frac{\mathrm{d}\gamma\vec{v}}{\mathrm{d}t} &= \gamma\frac{\mathrm{d}\vec{v}}{\mathrm{d}t} + \vec{v}\frac{\mathrm{d}\gamma}{\mathrm{d}t} \\
&= \gamma\frac{\mathrm{d}\vec{v}}{\mathrm{d}t} + \frac{\gamma^3 \vec{v}\vec{v}}{c^2}\cdot\frac{\mathrm{d}\vec{v}}{\mathrm{d}t}
\end{aligned}
$$

I agree that the issue here is that $\vec{v}\vec{v} \neq v^2$.

Also, I am thinking about switching to momentum in the relativistic case, as this holds:

$$
\frac{\mathrm{d}\vec{p}}{\mathrm{d}t} = q\left( \vec{E} + \vec{v}\times\vec{B} \right)
$$
where
$$
\vec{p} = \gamma(v) m_0 \vec{v}
$$

This is more common in the relativistic tracing case.

**Comment by henry2004y** [comment]
With the equation [here](http://spiff.rit.edu/classes/phys150/lectures/mom_rel/isolate_v.html), we can get the magnitude of v from p. The direction of v is the same as p. Then in the relativistic case, we can actually save (x, p) instead of (x, v), and obtain the Lorentz force from p on the RHS.
