### ISSUE TITLE
Breaking Interpolations.jl dependency in PkgBenchmark?

### ISSUE THREAD

**Issue by henry2004y** [henry2004y/TestParticle.jl#32]
After upgrading the Interpolations.jl compatibility version to v0.14 only, it accidentally broke the benchmark CI. The normal tests run fine though.

**Comment by TCLiuu** [comment]
I guess it may be a conflict between `BenchmarkCI` and the upgrade of packages at one branch. The procedure of BenchmarkCI is running `benchmark.jl` of this PR firstly and then checking out master branch with same missions. But the packages will only be installed once, thus after checkout the installed version of `Interpolations.jl` will be different with that declared in `Project.toml` of `master` branch.

I have a solution. Modifying the setting of benchmark ci and excluding the mission of benchmark when the name of PR includes some keywords like CompatHelper. Or just running a benchmark of this PR rather than a comparison with master when keywords exist.

**Comment by henry2004y** [comment]
Closed via #33
